#define WIFI_SSID "SSID"
#define WIFI_PASSWORD "PASS"

#define TARGET_HOST "192.168.1.100"
#define TARGET_PORT 3636

#define SENSOR_ID "SENSOR-ID-01"
#define USE_DEEP_SLEEP 1

#define READ_INTERVAL 60
#define KEEPALIVE_ON_EVERY_X_READS 14

#define INPUT_VOLTAGE_LOW_LIMIT 3000
#define ONE_WIRE_PIN 2

#define VALUE_CHANGE_TOLERANCE 0.25
#define VALUE_DECIMAL_PLACES 1

#define DEBUG_ENABLED 1

